language: node_js
node_js:
- node
- '8'
deploy:
  provider: npm
  email: mendrik76@gmail.com
  api_key:
    secure: ZLlZFxKNs44cEjPGocrweeSPb8RJihuZo0YMxUu1HUnUtrcrYWxRzoVCQ2UHyxuaG3Yjgv+G7gI2KLjIsoqArwMGNU29iLVz09BITfcMtyUPBnO6VAPs9jQFfjNYGRKitAI5gm5NwXTgH0+5yoE3m5ubv8wwVvDsP/7O5hKndVPSDTS0AwpvIfI1DpK0VBUrh2S8yaXUlmhwAKNKAKyFjiGf5fuZLRTiTqIaN9VBwZ0oA82oZPJ/uQVltsv0hHNB8HjH1fCbWhIf0kYDnO91s47wHXTOwT8tcWeg1wLjgWxeVx3PD5SB/9MN/C+fEFy5/if/YDtsQs3Ta+d0kFi4VkbwwB6kOeKuAXm9O4sm5GuRmtA0u3XlJRm4KH7mogi8nJaGpd/GGs2GNZr+Hnbeegnyr9z1jWN9UZoYn2fsKqKOGOWq7NGPVcXSk/S0kv7S7wFTHWFzkmPBAOqD1Jsz/k5GQOmCI5hI1XkJlhTDyII1K1jvcjoY5hO8g/pfxyVWsC7IRsLq9AnRZxNFawtHfyPdmcv1SzdSVo80qRrppa95OrRMGb21gbOXTVofgSizoAoUqvhxfQ+U6XHJsOBXMut90ORDQUFprzOwkkkrUqvf276Y1oYXSAVzc2VbcpQYCbwQ6mlxj9VYUdnqgGNlMkrAbhcOarts4lB2pOvm+KQ=
  on:
    repo: feather-ts/feather
